; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_protocol = esptool
; 添加项目 include 目录供 lib 中源码访问 pins.hpp
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -Iinclude -Isrc
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
lib_deps =
	adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
	adafruit/Adafruit GC9A01A
	adafruit/Adafruit BusIO
	zinggjm/GxEPD2
  
; 可选：串口监视器输出更友好
monitor_filters =
	colorize
	esp32_exception_decoder
