; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_protocol = esptool
lib_ldf_mode = deep+

build_flags = -DARDUINO_USB_CDC_ON_BOOT=1 -Iinclude -Isrc -Ilib
monitor_speed = 115200
monitor_port  = /dev/ttyACM0
upload_port   = /dev/ttyACM0
monitor_rts = 0
monitor_dtr = 0
lib_deps =
	adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
	adafruit/Adafruit GC9A01A
	adafruit/Adafruit BusIO
	zinggjm/GxEPD2
	bblanchon/ArduinoJson
	adafruit/Adafruit GFX Library 
  

monitor_filters =
	colorize
	esp32_exception_decoder
